---
- name: Configure Systemd
  hosts: plex.srv.3fr.uk
  become: true

  tasks:
  - name: ensure systemd-journal-remote package is installed
    ansible.builtin.apt:
      name: systemd-journal-remote

  - file:
      path: "/etc/systemd/system/systemd-journal-upload.service.d/"
      state: "directory"
      owner: root
      group: root
      mode: "0755"

  - template:
      src: ../../files/override.conf.j2
      dest: /etc/systemd/system/systemd-journal-upload.service.d/override.conf
      owner: root
      group: root
      mode: "0644"
 
  - template:
      src: ../../files/journal-upload.conf.j2
      dest: /etc/systemd/journal-upload.conf 
      owner: root
      group: root
      mode: "0644"
 
  - name: Start service
    systemd:
      name: systemd-journal-upload
      enabled: true
      state: started
      daemon_reload: true

  - name: Start service
    systemd:
      name: systemd-journal-remote
      enabled: false
      state: stopped
      daemon_reload: true
