---
- name: install caddy on backup
  hosts: backup.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: caddy
        image: registry.srv.3fr.uk/caddy
        pull: true
        hostname: caddy
        restart_policy: always
        default_host_ip: ""
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
          CADDY_DOCKER_CADDYFILE_PATH: "/config/caddy.static"
          CF_API_TOKEN:  "{{ cloudflare_api }}"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - caddy_config:/config
          - caddy_data:/data
          - /usr/share/urbackup/www:/usr/share/urbackup/www
        networks:
          - name: infra
        ports:
          - "80:80"
          - "443:443"
          - "443:443/udp"
