---
- name: install check_mk on topcat
  hosts: topcat.thunderweb.co.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: monitoring
        hostname: monitoring.thunderweb.co.uk
        image: checkmk/check-mk-raw:2.0.0-latest
        restart_policy: always
        volumes:
          - monitoring:/omd/sites
        ports:
          - "192.168.0.253:8080:5000"
        env:
          MAIL_RELAY_HOST: "192.168.0.253"
          CMK_SITE_ID: "cmk"
