---
- name: update docker compose stacks on docker1
  hosts: docker1.srv.3fr.uk
  gather_facts: false
  vars: 
    stack_name:
      - atuin
      - auth
      - immich
      - romm

  tasks:
    - name: pull latest containers on docker1
      ansible.builtin.command: 
        cmd: docker compose pull
        chdir: /home/scott/docker/{{ item }}
      loop: "{{ stack_name }}"
    - name: restart containers
      ansible.builtin.command: 
        cmd: docker compose up -d
        chdir: /home/scott/docker/{{ item }}
      loop: "{{ stack_name }}"
    - name: "Create CNAMEs"
      delegate_to: localhost
      loop: "{{ stack_name }}"
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: "{{ item }}.home.thunderweb.uk"
          type: CNAME
          cname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200