---
- name: install portainer-ee on docker1
  hosts: docker1.thunderweb.co.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: portainer
        image: portainer/portainer-ee:latest
        pull: true
        hostname: portainer
        restart_policy: always
        networks:
          - name: infra
        volumes:
          - portainer_data:/data
          - /var/run/docker.sock:/var/run/docker.sock
        ports:
          - "127.0.0.1:9000:9000"
