---
- name: install prowlarr on docker1
  hosts: docker1.thunderweb.co.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: prowlarr
        image: lscr.io/linuxserver/prowlarr:latest
        pull: true
        hostname: prowlarr
        restart_policy: always
        networks:
          - name: media
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Etc/UTC"
        volumes:
          - prowlarr_data:/config
        ports:
          - "127.0.0.1:9696:9696"
