---
- name: install stash on docker1
  hosts: docker1.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: stash
        image: ghcr.io/hotio/stash
        pull: true
        hostname: stash
        restart_policy: always
        networks:
          - name: media
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
          UMASK: "002"
        volumes:
          - /data/shared/_Sort:/data/shared/_Sort
          - /data/shared/_Sort/stash_data:/config
        labels:
          caddy: stash.home.thunderweb.uk
          caddy.import_0: httpauth
          caddy.import_1: accesslogs
          caddy.reverse_proxy: !unsafe "{{ upstreams 9999 }}"
