---
- name: install prowlarr on docker1
  hosts: docker1.srv.tfr.home
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: prowlarr
        image: lscr.io/linuxserver/prowlarr:latest
        pull: true
        hostname: prowlarr
        restart_policy: always
        networks:
          - name: media
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        volumes:
          - prowlarr_data:/config
        labels:
          caddy: prowlarr.home.thunderweb.uk
          caddy.import_0: httpauth
          caddy.reverse_proxy: !unsafe "{{ upstreams 9696 }}"
