---
- name: install ps5-mqtt on docker1
  hosts: docker1.thunderweb.co.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: ps5-mqtt
        image: ghcr.io/funkeyflo/ps5-mqtt/amd64:latest
        pull: true
        hostname: ps5-mqtt
        restart_policy: always
        network_mode: host
        env:
          CONFIG_PATH: "/config/options.json"
          DEBUG: "@ha:ps5:*"
        volumes:
          - ps5_mqtt:/config
        entrypoint: /config/run.sh