---
- name: install nextcloud on docker1
  hosts: docker1.thunderweb.co.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: nextcloud
        image: lscr.io/linuxserver/nextcloud:latest
        pull: true
        hostname: nextcloud
        restart_policy: always
        networks:
          - name: web
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Etc/UTC"
          DOCKER_MODS: "linuxserver/mods:nextcloud-memories|linuxserver/mods:nextcloud-mediadc"
        volumes:
          - nextcloud_config:/config
          - nextcloud_data:/data
        ports:
          - "127.0.0.1:8443:443"
