---
- name: install phpmyadmin on docker1
  hosts: docker1.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: phpmyadmin
        image: lscr.io/linuxserver/phpmyadmin:latest
        pull: true
        hostname: phpmyadmin
        restart_policy: always
        networks:
          - name: web
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
          PMA_ABSOLUTE_URI: "https://phpmyadmin.home.thunderweb.uk"
        volumes:
          - phpmyadmin_data:/config
        labels:
          caddy: phpmyadmin.home.thunderweb.uk
          caddy.import_0: httpauth
          caddy.import_1: accesslogs
          caddy.reverse_proxy: !unsafe "{{ upstreams 80 }}"