---
- name: install tautulli on docker1
  hosts: docker1.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: tautulli
        image: lscr.io/linuxserver/tautulli:latest
        pull: true
        hostname: tautulli
        restart_policy: always
        networks:
          - name: media
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        volumes:
          - tautulli_data:/config
        labels:
          caddy: tautulli.home.thunderweb.uk
          caddy.import_0: httpauth
          caddy.import_1: accesslogs
          caddy.reverse_proxy: !unsafe "{{ upstreams 8181 }}"
    - name: Create tautulli.home.thunderweb.uk CNAME
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: tautulli.home.thunderweb.uk
          type: CNAME
          cname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200