---
- name: install gitea on docker1
  hosts: docker1.thunderweb.co.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: gitea
        image: gitea/gitea:latest
        pull: true
        hostname: gitea
        restart_policy: always
        networks:
          - name: infra
        env:
          USER_UID: "1000"
          USER_GID: "1000"
          TZ: "Europe/London"
        volumes:
          - gitea_data:/data
          - /etc/timezone:/etc/timezone:ro
          - /etc/localtime:/etc/localtime:ro
        ports:
          - "2222:22"
        labels:
          caddy: git.home.thunderweb.uk
          caddy.import_0: httpauth
          caddy.reverse_proxy: !unsafe "{{ upstreams 3000 }}"