---
- name: install shlink on docker1
  hosts: docker1.thunderweb.co.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: shlink
        image: shlinkio/shlink:stable
        pull: true
        restart_policy: always
        hostname: shlink
        networks:
          - name: web
        env:
          DEFAULT_DOMAIN: "yag.me.uk"
          IS_HTTPS_ENABLED: "true"
          DB_DRIVER: "mysql"
          DB_USER: "shlink"
          DB_PASSWORD: "{{ shlink_mysql_pass }}"
          DB_NAME: "shlink"
          DB_HOST: "mariadb"
          GEOLITE_LICENSE_KEY: "{{ shlink_geolite }}"
        labels:
          caddy: yag.me.uk www.yag.me.uk
          caddy.reverse_proxy: !unsafe "{{ upstreams 8080 }}"