---
- name: install calibre-web on docker1
  hosts: docker1.thunderweb.co.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: calibre-web
        image: lscr.io/linuxserver/calibre-web:latest
        pull: true
        hostname: calibre-web
        restart_policy: always
        networks:
          - name: web
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
          DOCKER_MODS: "linuxserver/mods:universal-calibre"
        volumes:
          - calibre_config:/config
          - /data/shared/eBooks/Calibre:/books
          - /data/shared/:/data/shared
        labels:
          caddy: calibre.home.thunderweb.uk
          caddy.import_0: httpauth
          caddy.reverse_proxy: !unsafe "{{ upstreams 8083 }}"
