---
- name: install radarr on docker1
  hosts: docker1.thunderweb.co.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: radarr
        image: lscr.io/linuxserver/radarr:latest
        pull: true
        hostname: radarr
        restart_policy: always
        networks:
          - name: media
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Etc/UTC"
        volumes:
          - radarr_data:/config
          - /data/media:/data/media
          - /data/download/:/data/download
        labels:
          caddy: radarr.home.thunderweb.uk
          caddy.import_0: httpauth
          caddy.reverse_proxy: !unsafe "{{ upstreams 7878 }}"