---
- name: install jellyfin on docker2
  hosts: docker2.srv.tfr.home
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: jellyfin
        image: lscr.io/linuxserver/jellyfin:latest
        pull: true
        hostname: jellyfin
        restart_policy: always
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
          JELLYFIN_PublishedServerUrl: "192.168.0.252"
        volumes:
          - jellyfin_data:/config
          - /data/media:/data/media
        devices:
          - /dev/dri:/dev/dri
        ports:
          - "8096:8096"
          - "8920:8920"
          - "7359:7359/udp"
          - "1900:1900/udp"
