---
- name: install zigbee2mqtt on docker1
  hosts: docker1.thunderweb.co.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: zigbee2mqtt
        image: koenkk/zigbee2mqtt
        pull: true
        hostname: zigbee2mqtt
        restart_policy: always
        networks:
          - name: infra
        env:
          TZ: "Etc/UTC"
        volumes:
          - zigbee2mqtt_data:/app/data
          - /run/udev:/run/udev:ro
        devices:
          - "/dev/ttyUSB0:/dev/ttyUSB0"
        labels:
          caddy: zigbee.home.thunderweb.uk
          caddy.import_0: httpauth
          caddy.reverse_proxy: !unsafe "{{ upstreams 8080 }}"