---
- name: install coredns on docker1
  hosts: docker1.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: coredns
        image: coredns/coredns:latest
        pull: true
        hostname: coredns
        restart_policy: always
        networks:
          - name: web
        env:
          TZ: "Europe/London"
        volumes:
          - /home/scott/config/coredns/Corefile:/Corefile:ro
        ports:
          - "53:53/udp"
          - "53:53/tcp"
