---
- name: install homarr on docker1
  hosts: docker1.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: homarr
        image: ghcr.io/homarr-labs/homarr:latest
        pull: true
        hostname: homarr
        restart_policy: always
        networks:
          - name: web
        dns_servers:
          - 192.168.250.11
        env:
          AUTH_PROVIDERS: oidc
          AUTH_OIDC_ISSUER: "https://auth.thunderweb.uk"
          AUTH_OIDC_CLIENT_SECRET: "{{ homarr_oidc_secret }}"
          AUTH_OIDC_CLIENT_ID: "{{ homarr_oidc_client }}"
          AUTH_OIDC_CLIENT_NAME: "Authelia"  
          AUTH_OIDC_AUTO_LOGIN: "true"
          AUTH_OIDC_ADMIN_GROUP: "homarr_admin"
          AUTH_OIDC_OWNER_GROUP: "homarr_admin"
          NEXTAUTH_URL: "https://start.home.thunderweb.uk/"
          SECRET_ENCRYPTION_KEY: "{{ homarr_encryption }}"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - homarr_data:/appdata
        ports:
        labels:
          caddy: start.home.thunderweb.uk
          caddy.import_0: httpauth
          caddy.import_1: accesslogs
          caddy.reverse_proxy: !unsafe "{{ upstreams 7575 }}"
    - name: Create start.home.thunderweb.uk CNAME
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: start.home.thunderweb.uk
          type: CNAME
          cname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200