---
- name: install prowlarr on docker1
  hosts: docker1.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: prowlarr
        image: lscr.io/linuxserver/prowlarr:latest
        pull: true
        hostname: prowlarr
        restart_policy: always
        networks:
          - name: media
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        volumes:
          - prowlarr_data:/config
        labels:
          caddy: prowlarr.home.thunderweb.uk
          caddy.import_0: httpauth
          caddy.import_1: accesslogs
          caddy.reverse_proxy: !unsafe "{{ upstreams 9696 }}"
    - name: Create prowlarr.home.thunderweb.uk CNAME
      delegate_to: localhost
      sbarbett.pihole.local_cname:
        host: prowlarr.home.thunderweb.uk
        target: "{{ inventory_hostname }}"
        state: present
        url: "https://pihole.home.thunderweb.uk"
        password: "{{ pihole_admin }}"
