---
- name: update docker compose stacks on docker1
  hosts: docker1.srv.tfr.home
  gather_facts: false
  vars: 
    stack_name:
      - atuin
      - authelia
      - immich-app

  tasks:
    - name: pull latest containers on docker1
      ansible.builtin.command: 
        cmd: docker compose pull
        chdir: /home/scott/docker/{{ item }}
      loop: "{{ stack_name }}"
    - name: restart containers
      ansible.builtin.command: 
        cmd: docker compose up -d
        chdir: /home/scott/docker/{{ item }}
      loop: "{{ stack_name }}"
