---
- name: install portainer-ee on docker1
  hosts: docker1.srv.tfr.home
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: portainer
        image: portainer/portainer-ee:latest
        pull: true
        hostname: portainer
        restart_policy: always
        networks:
          - name: infra
        volumes:
          - portainer_data:/data
          - /var/run/docker.sock:/var/run/docker.sock
        labels:
          caddy: portainer.home.thunderweb.uk
          caddy.import_0: httpauth
          caddy.reverse_proxy: !unsafe "{{ upstreams 9000 }}"