---
- name: install nextcloud on docker1
  hosts: docker1.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: nextcloud
        image: lscr.io/linuxserver/nextcloud:latest
        pull: true
        hostname: nextcloud
        restart_policy: always
        networks:
          - name: web
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        volumes:
          - nextcloud_config:/config
          - nextcloud_data:/data
        labels:
          caddy: drive.thunderweb.uk
          caddy.import_0: accesslogs
          caddy.reverse_proxy: !unsafe "{{ upstreams 443 }}"
          caddy.reverse_proxy.transport: "http"
          caddy.reverse_proxy.transport.tls_insecure_skip_verify: ""
    - name: Create drive.thunderweb.uk ANAME
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: drive.thunderweb.uk
          type: ANAME
          aname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200