---
- name: install homarr on docker1
  hosts: docker1.srv.tfr.home
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: homarr
        image: ghcr.io/ajnart/homarr:latest
        pull: true
        hostname: homarr
        restart_policy: always
        networks:
          - name: web
        env:
          PUID: "1000"
          PGID: "1000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - homarr_configs:/app/data/configs
          - homarr_icons:/app/public/icons
          - homarr_data:/data
        ports:
        labels:
          caddy: start.home.thunderweb.uk
          caddy.import_0: httpauth
          caddy.reverse_proxy: !unsafe "{{ upstreams 7575 }}"