---
- name: install gitea on docker1
  hosts: docker1.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: gitea
        image: gitea/gitea:latest
        pull: true
        hostname: gitea
        restart_policy: always
        networks:
          - name: infra
        env:
          USER_UID: "1000"
          USER_GID: "1000"
          TZ: "Europe/London"
        volumes:
          - gitea_data:/data
          - /etc/timezone:/etc/timezone:ro
          - /etc/localtime:/etc/localtime:ro
        ports:
          - "2222:22"
        labels:
          caddy: git.home.thunderweb.uk
          caddy.import_0: httpauth
          caddy.import_1: accesslogs
          caddy.reverse_proxy: !unsafe "{{ upstreams 3000 }}"
          caddy.rewrite: '/user/login /user/oauth2/authelia'
    - name: Create git.home.thunderweb.uk CNAME
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: git.home.thunderweb.uk
          type: CNAME
          cname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200