---
- name: install plex on docker2
  hosts: docker2.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: plex
        image: lscr.io/linuxserver/plex:latest
        pull: true
        hostname: plex
        restart_policy: always
        network_mode: host
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
          VERSION: "latest"
          # PLEX_CLAIM: ""
        volumes:
          - plex_data:/config
          - threadfin_conf:/home/threadfin/conf
          - /data/media:/data/media
        devices:
          - /dev/dri:/dev/dri
