---
- name: install overseerr on docker1
  hosts: docker1.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: overseerr
        image: lscr.io/linuxserver/overseerr:latest
        pull: true
        hostname: overseerr
        restart_policy: always
        networks:
          - name: media
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        volumes:
          - overseerr_data:/config
        labels:
          caddy: overseerr.home.thunderweb.uk
          caddy.import_0: httpauth
          caddy.reverse_proxy: !unsafe "{{ upstreams 5055 }}"