---
- name: install IT Tools on docker1
  hosts: docker1.thunderweb.co.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: ittools
        image: ghcr.io/corentinth/it-tools:latest
        pull: true
        hostname: ittools
        restart_policy: always
        networks:
          - name: web
        labels:
          caddy: tools.home.thunderweb.uk
          caddy.import_0: httpauth
          caddy.reverse_proxy: !unsafe "{{ upstreams 80 }}"