---
- name: install munin on docker1
  hosts: docker1.thunderweb.co.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: munin
        image: aheimsbakk/munin-alpine
        pull: true
        hostname: munin
        restart_policy: always
        networks:
          - name: infra
        env:
          NODES: "nas1.thunderweb.co.uk:192.168.0.254 docker1.thunderweb.co.uk:192.168.0.253 raspberrypi.thunderweb.co.uk:192.168.0.2"
        volumes:
          - munin_config:/etc/munin/munin-conf.d
          - munin_plugin:/etc/munin/plugin-conf.d
          - munin_lib:/var/lib/munin
          - munin_log:/var/log/munin
        labels:
          caddy: monitoring.home.thunderweb.uk monitoring.thunderweb.uk
          caddy.import_0: httpauth
          caddy.reverse_proxy: !unsafe "{{ upstreams 80 }}"
          caddy.redir: / https://monitoring.home.thunderweb.uk/munin/