---
- name: install docker registry on docker1
  hosts: docker1.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: registry
        image: registry:2
        pull: true
        hostname: registry
        restart_policy: always
        networks:
          - name: infra
        volumes:
          - registry_repo:/var/lib/registry
        env:
          REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: "['*']"
          REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: '[Docker-Content-Digest]'
          REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: '[HEAD,GET,OPTIONS,DELETE]'
          REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials: '[true]'
          REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: '[Authorization,Accept,Cache-Control]'
    
    - community.docker.docker_container:
        name: registry-ui
        image: joxit/docker-registry-ui:main
        pull: true
        hostname: registry-ui
        restart_policy: always
        networks:
          - name: infra
        env:
          SINGLE_REGISTRY: "true"
          REGISTRY_TITLE: "Docker Registry UI"
          REGISTRY_URL: "https://registry.srv.3fr.uk"
          DELETE_IMAGES: "true"
          SHOW_CONTENT_DIGEST: "true"
          SHOW_CATALOG_NB_TAGS: "true"
          CATALOG_MIN_BRANCHES: "1"
          CATALOG_MAX_BRANCHES: "1"
          TAGLIST_PAGE_SIZE: "100"
          CATALOG_ELEMENTS_LIMIT: "1000"
          NGINX_PROXY_PASS_URL: http://registry:5000
        labels:
          caddy: registry.srv.3fr.uk
          caddy.import_0: httpauthold
          caddy.import_1: accesslogs
          caddy.reverse_proxy: !unsafe "{{ upstreams 80 }}"
    - name: Create registry.srv.3fr.uk CNAME
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: registry.srv.3fr.uk
          type: CNAME
          cname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200