---
- name: install caddy on docker1
  hosts: docker1.thunderweb.co.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: caddy
        image: caddy:custom
        pull: false
        hostname: caddy
        restart_policy: always
        networks:
          - name: web
          - name: infra
          - name: media
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
          CADDY_DOCKER_CADDYFILE_PATH: "/config/caddy.static"
          CF_API_TOKEN:  "{{ cloudflare_api }}"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - caddy_config:/config
          - caddy_data:/data
          - wordpress_data:/var/www/html
        ports:
          - "80:80"
          - "443:443"
          - "443:443/udp"
