---
- name: install wallos on docker1
  hosts: docker1.srv.tfr.home
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: wallos
        image: bellamy/wallos:latest
        pull: true
        hostname: wallos
        restart_policy: always
        networks:
          - name: web
        env:
          TZ: "Europe/London"
        volumes:
          - wallos_db:/var/www/html/db
          - wallos_logos:/var/www/html/images/uploads/logos
        labels:
          caddy: wallos.home.thunderweb.uk
          caddy.import_0: httpauth
          caddy.reverse_proxy: !unsafe "{{ upstreams 80 }}"
