---
- name: install munin on docker1
  hosts: docker1.srv.tfr.home
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: munin
        image: aheimsbakk/munin-alpine
        pull: true
        hostname: munin
        restart_policy: always
        networks:
          - name: infra
        env:
          NODES: "mailgateway1.srv.tfr.home:192.168.250.25 nas1.srv.tfr.home:192.168.250.101 docker1.srv.tfr.home:192.168.250.11 docker2.srv.tfr.home:192.168.250.12 pihole.srv.tfr.home:192.168.250.53 proxmox1.srv.tfr.home:192.168.250.111 proxmox2.srv.tfr.home:192.168.250.112 vps1.thunderweb.uk:192.168.2.2 vps2.thunderweb.uk:192.168.2.3 vps3.thunderweb.uk:192.168.2.4"
          TZ: "Europe/London"
        volumes:
          - munin_config:/etc/munin/munin-conf.d
          - munin_plugin:/etc/munin/plugin-conf.d
          - munin_lib:/var/lib/munin
          - munin_log:/var/log/munin
        labels:
          caddy: monitoring.home.thunderweb.uk monitoring.thunderweb.uk
          caddy.import_0: httpauth
          caddy.reverse_proxy: !unsafe "{{ upstreams 80 }}"
          caddy.redir: / https://monitoring.home.thunderweb.uk/munin/
