---
- name: install heimdall on docker1
  hosts: docker1.thunderweb.co.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: heimdall
        image: lscr.io/linuxserver/heimdall:latest
        pull: true
        hostname: heimdall
        restart_policy: always
        networks:
          - name: web
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Etc/UTC"
          APP_URL: "https://start.home.thunderweb.uk/"
        volumes:
          - heimdall_data:/config
        ports:
        labels:
          caddy: start.home.thunderweb.uk
          caddy.import_0: httpauth
          caddy.import_1: cloudflare
          caddy.reverse_proxy: !unsafe "{{ upstreams 80 }}"