---
- name: install sonarr on docker1
  hosts: docker1.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: sonarr
        image: lscr.io/linuxserver/sonarr:latest
        pull: true
        hostname: sonarr
        restart_policy: always
        networks:
          - name: media
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        volumes:
          - sonarr_data:/config
          - /data/media:/data/media
          - /data/download/:/data/download
        labels:
          caddy: sonarr.home.thunderweb.uk
          caddy.import_0: httpauth
          caddy.reverse_proxy: !unsafe "{{ upstreams 8989 }}"