---
- name: install gitlab on topcat
  hosts: topcat.thunderweb.co.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: gitlab
        image: gitlab/gitlab-ce:latest
        hostname: gitlab.thunderweb.co.uk
        restart_policy: always
        volumes:
          - gitlab_config:/etc/gitlab
          - gitlab_logs:/var/log/gitlab
          - gitlab_data:/var/opt/gitlab
        ports:
          - "127.0.0.1:9080:80"
          - "2222:22"
