---
- name: install qbitrr on mini1.srv.3fr.uk
  hosts: mini1.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: qbitrr
        image: feramance/qbitrr:latest
        pull: true
        init: true
        hostname: qbitrr
        restart_policy: always
        networks:
          - name: web
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        volumes:
          - qbitrr_data:/config
          - /data:/data
        labels:
          caddy_1: qbitrr.svc.3fr.uk
          caddy_1.import: accesslogs
          caddy_1.reverse_proxy: !unsafe "{{ upstreams 6969 }}"
    - name: Create qbitrr.svc.3fr.uk CNAME
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: qbitrr.svc.3fr.uk
          type: CNAME
          ttl: 300
          cname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200