---
- name: install pairdrop on mini1
  hosts: mini1.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: pairdrop
        image: lscr.io/linuxserver/pairdrop:latest
        pull: true
        hostname: pairdrop
        restart_policy: always
        networks:
          - name: web
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        labels:
          caddy_0: drop.home.thunderweb.uk
          caddy_0.redir: https://drop.svc.3fr.uk{uri}
          caddy_1: drop.svc.3fr.uk
          caddy_1.import_0: accesslogs
          caddy_1.reverse_proxy: !unsafe "{{ upstreams 3000 }}"
    - name: Create drop.svc.3fr.uk CNAME
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: drop.svc.3fr.uk
          type: CNAME
          ttl: 3600
          cname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200