---
- name: install gitea on mini1.srv.3fr.uk
  hosts: mini1.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: gitea
        image: gitea/gitea:latest
        pull: true
        hostname: gitea
        restart_policy: always
        networks:
          - name: web
        env:
          USER_UID: "1000"
          USER_GID: "1000"
          TZ: "Europe/London"
        volumes:
          - gitea_data:/data
          - /etc/timezone:/etc/timezone:ro
          - /etc/localtime:/etc/localtime:ro
        ports:
          - "2222:22"
        labels:
          caddy_0: git.home.thunderweb.uk
          caddy_0.redir: https://git.svc.3fr.uk{uri}
          caddy_1: git.svc.3fr.uk
          caddy_1.import_1: accesslogs
          caddy_1.reverse_proxy: !unsafe "{{ upstreams 3000 }}"
          caddy_1.rewrite: '/user/login /user/oauth2/authelia'
        memory: 1G
        memory_swap: 1G
    - name: Create git.svc.3fr.uk CNAME
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: git.svc.3fr.uk
          type: CNAME
          ttl: 3600
          cname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200