---
- name: install medialyze on mini1.srv.3fr.uk
  hosts: mini1.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: medialyze
        image: ghcr.io/frederikemmer/medialyze:latest
        pull: true
        hostname: medialyze
        restart_policy: always
        networks:
          - name: web
        env:
          TZ: "Europe/London"
          PUID: "1000"
          PGID: "1000"
        volumes:
          - medialyze_data:/config
          - /data/media:/media/data:ro
          - /data2/media:/media/data2:ro
        labels:
          caddy_1: medialyze.svc.3fr.uk
          caddy_1.import_0: accesslogs
          caddy_1.reverse_proxy: !unsafe "{{ upstreams 8080 }}"
    - name: Create medialyze.svc.3fr.uk CNAME
      delegate_to: localhost
      no_log: true
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: medialyze.svc.3fr.uk
          type: CNAME
          ttl: 3600
          cname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200