---
- name: install homarr on mini1.srv.3fr.uk
  hosts: mini1.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: homarr
        image: ghcr.io/homarr-labs/homarr:latest
        pull: true
        hostname: homarr
        restart_policy: always
        networks:
          - name: web
        env:
          AUTH_PROVIDERS: oidc
          AUTH_OIDC_ISSUER: "https://auth.3fr.uk"
          AUTH_OIDC_CLIENT_SECRET: "{{ homarr_oidc_secret }}"
          AUTH_OIDC_CLIENT_ID: "{{ homarr_oidc_client }}"
          AUTH_OIDC_CLIENT_NAME: "Authelia"  
          AUTH_OIDC_AUTO_LOGIN: "true"
          AUTH_OIDC_ADMIN_GROUP: "homarr_admin"
          AUTH_OIDC_OWNER_GROUP: "homarr_admin"
          NEXTAUTH_URL: "https://start.svc.3fr.uk/"
          SECRET_ENCRYPTION_KEY: "{{ homarr_encryption }}"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - homarr_data:/appdata
        ports:
        labels:
          caddy_0: start.home.thunderweb.uk
          caddy_0.redir: https://start.svc.3fr.uk{uri}
          caddy_1: start.svc.3fr.uk
          caddy_1.import_1: accesslogs
          caddy_1.reverse_proxy: !unsafe "{{ upstreams 7575 }}"
        memory: 1G
    - name: Create start.svc.3fr.uk CNAME
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: start.svc.3fr.uk
          type: CNAME
          ttl: 3600
          cname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200