---
- name: install portainer-ee on nas1
  hosts: nas1.thunderweb.co.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: portainer
        image: portainer/portainer-ee:latest
        pull: true
        hostname: portainer
        restart_policy: always
        volumes:
          - portainer_data:/data
          - /var/run/docker.sock:/var/run/docker.sock
        ports:
          - "9000:9000"
