---
- name: install tautulli on nas1
  hosts: nas1.thunderweb.co.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: tautulli
        image: lscr.io/linuxserver/tautulli:latest
        pull: true
        hostname: tautulli
        restart_policy: always
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Etc/UTC"
        volumes:
          - tautulli_data:/config
        ports:
          - "8181:8181"
