---
- name: install heimdall on nas1
  hosts: nas1.thunderweb.co.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: heimdall
        image: lscr.io/linuxserver/heimdall:latest
        pull: true
        hostname: heimdall
        restart_policy: always
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Etc/UTC"
          APP_URL: "https://start.home.thunderweb.uk/"
        volumes:
          - heimdall_data:/config
        ports:
          - 8080:80
