---
- name: install zigbee2mqtt on nas1
  hosts: nas1.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: zigbee2mqtt
        image: koenkk/zigbee2mqtt
        pull: true
        ports:
          - "8082:8080"
        hostname: zigbee2mqtt
        restart_policy: always
        env:
          TZ: "Europe/London"
        volumes:
          - zigbee2mqtt_data:/app/data
          - /run/udev:/run/udev:ro
        devices:
          - "/dev/ttyUSB0:/dev/ttyUSB0"