---
- name: install duplicati on nas1
  hosts: nas1.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: duplicati
        image: lscr.io/linuxserver/duplicati:latest
        pull: true
        hostname: duplicati
        restart_policy: always
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        volumes:
          - duplicati_data:/config
          - duplicati_source:/source
          - duplicati_backups:/backups
          - /data/icloud/photos:/data/icloud/photos
          - /data/backups/mail:/data/backups/mail
          - /data/backups/nextcloud:/data/backups/nextcloud
          - /data/backups/applications:/data/backups/applications
          - /data/shared:/data/shared
        labels:
          caddy: duplicati.home.thunderweb.uk
          caddy.reverse_proxy: !unsafe "{{ upstreams 8200 }}"
    - name: Create duplicati.home.thunderweb.uk CNAME
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: duplicati.home.thunderweb.uk
          type: CNAME
          cname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200