---
- name: install sonarr on nas1
  hosts: nas1.thunderweb.co.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: sonarr
        image: lscr.io/linuxserver/sonarr:latest
        hostname: sonarr
        restart_policy: always
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Etc/UTC"
        volumes:
          - sonarr_data:/config
          - /data/media:/data/media
          - /data/download/:/data/download
        ports:
          - "8989:8989"
