---
- name: install zigbee2mqtt on nas1
  hosts: nas1.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: zigbee2mqtt
        image: koenkk/zigbee2mqtt
        pull: true
        ports:
          - "8082:8080"
        hostname: zigbee2mqtt
        restart_policy: always
        env:
          TZ: "Europe/London"
        volumes:
          - zigbee2mqtt_data:/app/data
          - /run/udev:/run/udev:ro
        devices:
          - "/dev/ttyUSB0:/dev/ttyUSB0"
        labels:
          caddy: zigbee.home.thunderweb.uk
          caddy.import_0: httpauth
          caddy.import_1: accesslogs
          caddy.reverse_proxy: !unsafe "{{ upstreams 8080 }}"

    - name: Create zigbee.home.thunderweb.uk CNAME
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: zigbee.home.thunderweb.uk
          type: CNAME
          cname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200