---
- name: install duplicati on nas1
  hosts: nas1.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: duplicati
        image: lscr.io/linuxserver/duplicati:latest
        pull: true
        hostname: duplicati
        restart_policy: always
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        volumes:
          - duplicati_data:/config
          - duplicati_source:/source
          - duplicati_backups:/backups
          - /data:/data
        labels:
          caddy: duplicati.home.thunderweb.uk
          caddy.reverse_proxy: !unsafe "{{ upstreams 8200 }}"
