---
- name: install duplicati on nas1
  hosts: nas1.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: duplicati
        image: lscr.io/linuxserver/duplicati:latest
        pull: true
        hostname: duplicati
        restart_policy: always
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        volumes:
          - duplicati_data:/config
          - duplicati_source:/source
          - duplicati_backups:/backups
          - /data:/data
        networks:
          - name: web
        labels:
          caddy_0: duplicati.home.thunderweb.uk
          caddy_0.redir: https://duplicati.svc.3fr.uk{uri}
          caddy_1: duplicati.svc.3fr.uk
          caddy_1.reverse_proxy: !unsafe "{{ upstreams 8200 }}"
    - name: Create duplicati.home.thunderweb.uk CNAME
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: duplicati.svc.3fr.uk
          type: CNAME
          cname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200