---
- name: install unpackerr on nas1
  hosts: nas1.thunderweb.co.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: unpackerr
        image: golift/unpackerr
        pull: true
        hostname: unpackerr
        restart_policy: always
        volumes:
          - /data/download/:/data/download
          - /data/media/download:/data/media/download
          - /home/scott/configs/unpackerr:/config
