---
- name: install portainer_agent on portainerclients group
  hosts: portainerclients
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: portainer_agent
        image: portainer/agent
        pull: true
        restart_policy: always
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker/volumes:/var/lib/docker.volumes
        ports:
          - 9001:9001

