---
- name: install pihole on pihole
  hosts: pihole.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: pihole
        image: pihole/pihole:latest
        pull: true
        hostname: pihole
        restart_policy: always
        network_mode: host
        shm_size: 256M
        env:
          TZ: "Europe/London"
          FTLCONF_webserver_port: "80"
          FTLCONF_dhcp_start: "192.168.0.150"
          FTLCONF_dhcp_end: "192.168.0.200"
          FTLCONF_dhcp_router: "192.168.0.1"
          FTLCONF_dhcp_leaseTime: "24"
          FTLCONF_dns_domain: "3fr.uk"
          FTLCONF_dns_upstreams: "127.0.0.1#5054"
          # FTLCONF_webserver_api_password: ""
          LOCAL_IPV4: "192.168.250.53"
        volumes:
          - pihole_etc:/etc/pihole
          - pihole_dnsmasq:/etc/dnsmasq.d
          - pihole_tftpboot:/tftpboot/
          - pihole_log:/var/log/pihole/
        capabilities:
          - NET_ADMIN
