---
- name: install cloudflared on pihole
  hosts: pihole.tfr.home
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: cloudflared
        image: visibilityspots/cloudflared:latest
        pull: true
        network_mode: host
        restart_policy: always
