---
- name: install netalertx on pihole
  hosts: pihole.srv.tfr.home
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: netalertx
        image: jokobsk/netalertx:latest
        hostname: netalertx
        pull: true
        network_mode: host
        restart_policy: always
        env:
          port: "20211"
          TZ: "Europe/London"
        volumes:
          - /etc/pihole:/etc/pihole
          - netalertx_db:/app/db
          - netalertx_config:/app/config
