---
- name: install jellyfin on plex
  hosts: plex.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: jellyfin
        image: lscr.io/linuxserver/jellyfin:latest
        pull: true
        hostname: jellyfin
        restart_policy: always
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Etc/UTC"
          JELLYFIN_PublishedServerUrl: "https://jellyfin.srv.3fr.uk"
        networks:
          - name: web
        volumes:
          - jellyfin_config:/config
          - /data:/data
          - /data2:/data2
        labels:
          caddy: jellyfin.srv.3fr.uk
          caddy.reverse_proxy: !unsafe "{{ upstreams 8096 }}"
    - name: Create jellyfin.srv.3fr.uk CNAME
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: jellyfin.srv.3fr.uk
          type: CNAME
          cname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200