---
- name: install jellyfin on plex
  hosts: plex.srv.3fr.uk
  gather_facts: true
  tasks:
    - community.docker.docker_container:
        name: jellyfin
        image: lscr.io/linuxserver/jellyfin:latest
        pull: true
        hostname: jellyfin
        restart_policy: always
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Etc/UTC"
          JELLYFIN_PublishedServerUrl: "{{ ansible_enp6s18.ipv4.address }}"
          DOCKER_MODS: "linuxserver/mods:jellyfin-amd"
        networks:
          - name: web
        volumes:
          - jellyfin_config:/config
          - /data:/data
        devices:
          - /dev/dri:/dev/dri
          - /dev/kfd:/dev/kfd
        labels:
          caddy: jellyfin.srv.3fr.uk
          caddy.reverse_proxy: !unsafe "{{ upstreams 8096 }}"