---
- name: install radarr on plex.srv.3fr.uk
  hosts: plex.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: radarr
        image: lscr.io/linuxserver/radarr:latest
        pull: true
        hostname: radarr
        restart_policy: always
        networks:
          - name: web
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        volumes:
          - radarr_data:/config
          - /data/media:/data/media
          - /data/download/:/data/download
          - /data2/media:/data2/media
        labels:
          caddy: radarr.home.thunderweb.uk
          caddy.import_0: accesslogs
          caddy.reverse_proxy: !unsafe "{{ upstreams 7878 }}"
    - name: Create radarr.home.thunderweb.uk CNAME
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: radarr.home.thunderweb.uk
          type: CNAME
          cname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200