---
- name: install shlink on topcat
  hosts: nas1.thunderweb.co.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: shlink
        image: shlinkio/shlink:stable
        restart_policy: always
        ports:
          - "127.0.0.1:8080:8080"
        env:
          DEFAULT_DOMAIN: "yag.me.uk"
          IS_HTTPS_ENABLED: "true"
          DB_DRIVER: "mysql"
          DB_USER: "shlink"
          DB_PASSWORD: "{{ shlink_mysql_pass }}"
          DB_NAME: "shlink"
          DB_HOST: "192.168.0.254"
          GEOLITE_LICENSE_KEY: "{{ shlink_geolite }}"
