---
- name: install portainer_agent on vps1
  hosts: vps1.thunderweb.uk 
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: portainer_agent
        image: portainer/agent
        pull: true
        restart_policy: always
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker/volumes:/var/lib/docker.volumes
        ports:
          - 192.168.2.2:9001:9001

