---
- name: install uptime kuma on vps1
  hosts: vps1.thunderweb.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: uptimekuma
        image: louislam/uptime-kuma:latest
        pull: true
        hostname: uptimekuma
        restart_policy: always
        networks:
          - name: web
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        volumes:
          - uptimekuma_data:/app/data 
        labels:
          caddy: kuma.thunderweb.uk
          caddy.import_0: httpauth
          caddy.reverse_proxy: !unsafe "{{ upstreams 3001 }}"
