---
- name: install uptime kuma on vps2
  hosts: vps2.thunderweb.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: uptimekuma
        image: louislam/uptime-kuma:latest
        pull: true
        hostname: uptimekuma
        restart_policy: always
        networks:
          - name: web
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        memory: 256M
        memory_swap: 256M
        volumes:
          - uptimekuma_data:/app/data 
        labels:
          caddy: kuma.thunderweb.uk status.thunderweb.uk
          caddy.import_0: httpauth
          caddy.reverse_proxy: !unsafe "{{ upstreams 3001 }}"
