---
- name: install linkstack on vps3
  hosts: vps3.thunderweb.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: linkstack
        image: linkstackorg/linkstack:latest
        pull: true
        hostname: linkstack
        restart_policy: always
        networks:
          - name: web
        volumes:
          - linkstack_data:/htdocs
        env:
          TZ: "Europe/London"
          SERVER_ADMIN: 'clar2242@me.com'
          HTTP_SERVER_NAME: 'comeandclick.me.uk'
          HTTPS_SERVER_NAME: 'comeandclick.me.uk'
          LOG_LEVEL: 'info'
          PHP_MEMORY_LIMIT: '256M'
          UPLOAD_MAX_FILESIZE: '8M'
        labels:
          caddy: comeandclick.me.uk www.comeandclick.me.uk
          caddy.import_0: accesslogs
          caddy.reverse_proxy: !unsafe "{{ upstreams 443 }}"
          caddy.reverse_proxy.transport: "http"
          caddy.reverse_proxy.transport.tls_insecure_skip_verify: ""