---
- name: install dozzle agent on external hosts
  hosts: externalboxes
  gather_facts: true
  tasks:
    - community.docker.docker_container:
        name: dozzle_agent
        image: amir20/dozzle:latest
        pull: true
        hostname: dozzle_agent
        restart_policy: always
        command: agent
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
        ports:
          - "{{ ansible_wg0.ipv4.address }}:7007:7007"
