---
- name: install portainer_agent on vps boxes
  hosts: externalboxes
  gather_facts: true
  tasks:
    - community.docker.docker_container:
        name: portainer_agent
        image: portainer/agent
        pull: true
        restart_policy: always
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker/volumes:/var/lib/docker.volumes
        ports:
          - "{{ ansible_wg0.ipv4.address }}:9001:9001"

