---
- name: install caddy on webdev
  hosts: webdev.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: caddy
        image: registry.srv.3fr.uk/caddy
        pull: true
        hostname: caddy
        restart_policy: always
        default_host_ip: ""
        dns_servers:
          - 8.8.8.8
          - 1.1.1.1
          - 8.8.4.4
        networks:
          - name: web
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
          CADDY_DOCKER_CADDYFILE_PATH: "/config/caddy.static"
          CF_API_TOKEN:  "{{ cloudflare_api }}"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - caddy_config:/config
          - caddy_data:/data
          - caddy_logs:/var/log/caddy
          - wordpress_data_scottclark:/var/www/html
        ports:
          - "80:80"
          - "443:443"
          - "443:443/udp"
