---
- name: Install Wazuh Agent
  hosts: wazuhagents
  become: true

  tasks:
  - name: Download the installation package
    get_url:
      url: https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.14.5-1_amd64.deb
      dest: ~/wazuh-agent.deb

  - name: Install Wazuh
    shell: WAZUH_MANAGER='192.168.250.3' dpkg -i ~/wazuh-agent.deb

  - name: Cleanup installation package
    file:
      path: ~/wazuh-agent.deb
      state: absent

  - name: Start service
    systemd:
      name: wazuh-agent
      enabled: true
      state: started
      daemon_reload: true

  - name: copy DockerListener to host
    ansible.builtin.copy:
      src: ../files/wazuh/DockerListener
      dest: /var/ossec/wodles/docker/DockerListener
      owner: root
      group: wazuh
      mode: '0750'

  - name: copy install.sh to host
    ansible.builtin.copy:
      src: ../files/wazuh/install.sh
      dest: /root/install.sh
      owner: root
      group: wazuh
      mode: '0750'

  - name: Configure Wazuh
    shell: /root/install.sh

  - name: Restart Wazuh
    systemd:
      name: wazuh-agent
      enabled: true
      state: restarted
      daemon_reload: true    
