---
- import_playbook: docker/_shared/caddy_proxy.yml
- import_playbook: docker/_shared/docker_socket_proxy.yml
- import_playbook: docker/_shared/portainer_agent.yml
- import_playbook: docker/_vpsshared/portainer_agent.yml
- import_playbook: docker/dns/mariadb.yml
- import_playbook: docker/docker0/calibreweb.yml
- import_playbook: docker/docker0/flaresolverr.yml
- import_playbook: docker/docker0/ittools.yml
- import_playbook: docker/docker0/komga.yml
- import_playbook: docker/docker0/medialyze.yml
- import_playbook: docker/docker0/prowlarr.yml
- import_playbook: docker/docker0/radarr.yml
- import_playbook: docker/docker0/reaparr.yml
- import_playbook: docker/docker0/seerr.yml
- import_playbook: docker/docker0/sonarr.yml
- import_playbook: docker/docker0/stash.yml
- import_playbook: docker/docker0/tautulli.yml
- import_playbook: docker/docker1/changedetection.yml
- import_playbook: docker/docker1/homarr.yml
- import_playbook: docker/docker1/homepage.yml
- import_playbook: docker/docker1/n8n.yml
- import_playbook: docker/docker1/openbooks.yml
- import_playbook: docker/docker1/pairdrop.yml
- import_playbook: docker/docker1/speedtest.yml
- import_playbook: docker/dockflare/_compose_updates.yml
- import_playbook: docker/mini0/_compose_updates.yml
- import_playbook: docker/mini0/caddy_proxy.yml
- import_playbook: docker/mini1/_compose_updates_svc.yml
- import_playbook: docker/mini1/caddy.yml
- import_playbook: docker/mini1/filezilla.yml
- import_playbook: docker/mini1/gitea.yml
- import_playbook: docker/mini1/mariadb.yml
- import_playbook: docker/mini1/nextcloud.yml
- import_playbook: docker/mini1/phpmyadmin.yml
- import_playbook: docker/mini1/portainer.yml
- import_playbook: docker/mini1/registry.yml
- import_playbook: docker/mini1/wordpress.yml
- import_playbook: docker/monitoring/_compose_updates_svc.yml
- import_playbook: docker/monitoring/munin.yml
- import_playbook: docker/monitoring/uptimekuma.yml
- import_playbook: docker/nas1/_compose_stacks.yml
- import_playbook: docker/nas1/caddy.yml
- import_playbook: docker/nas1/duplicati.yml
- import_playbook: docker/nas1/icloudpd.yml
- import_playbook: docker/nas1/jellyfin.yml
- import_playbook: docker/nas1/unpackerr.yml
- import_playbook: docker/nas1/zigbee2mqtt.yml
- import_playbook: docker/vps1/_compose_updates.yml
- import_playbook: docker/vps1/caddy_proxy.yml
- import_playbook: docker/vps2/caddy_proxy.yml
- import_playbook: docker/vps2/coredns.yml
- import_playbook: docker/vps2/linkstack.yml
- import_playbook: docker/vps2/mariadb.yml
- import_playbook: docker/vps2/shlink.yml
- import_playbook: docker/wazuh/caddy_proxy.yml
- import_playbook: docker_prune.yml
