---
- import_playbook: docker/dns_caddy_proxy.yml
- import_playbook: docker/dns_mariadb.yml
- import_playbook: docker/internal_docker_socket_proxy.yml
- import_playbook: docker/mini0_caddy_proxy.yml
- import_playbook: docker/mini0_compose_updates.yml
- import_playbook: docker/mini0_jellyfin.yml
- import_playbook: docker/mini1_caddy.yml
- import_playbook: docker/mini1_calibreweb.yml
- import_playbook: docker/mini1_changedetection.yml
- import_playbook: docker/mini1_compose_updates_home.yml
- import_playbook: docker/mini1_compose_updates_srv.yml
- import_playbook: docker/mini1_compose_updates_svc.yml
- import_playbook: docker/mini1_gitea.yml
- import_playbook: docker/mini1_homarr.yml
- import_playbook: docker/mini1_homepage.yml
- import_playbook: docker/mini1_mariadb.yml
- import_playbook: docker/mini1_nextcloud.yml
- import_playbook: docker/mini1_openbooks.yml
- import_playbook: docker/mini1_pairdrop.yml
- import_playbook: docker/mini1_phpmyadmin.yml
- import_playbook: docker/mini1_portainer.yml
- import_playbook: docker/mini1_prowlarr.yml
- import_playbook: docker/mini1_radarr.yml
- import_playbook: docker/mini1_reaparr.yml
- import_playbook: docker/mini1_registry.yml
- import_playbook: docker/mini1_seerr.yml
- import_playbook: docker/mini1_sonarr.yml
- import_playbook: docker/mini1_speedtest.yml
- import_playbook: docker/mini1_stash.yml
- import_playbook: docker/mini1_tautulli.yml
- import_playbook: docker/mini1_tools.yml
- import_playbook: docker/mini1_wordpress.yml
- import_playbook: docker/monitoring_caddy_proxy.yml
- import_playbook: docker/monitoring_munin.yml
- import_playbook: docker/monitoring_uptimekuma.yml
- import_playbook: docker/nas1_caddy.yml
- import_playbook: docker/nas1_duplicati.yml
- import_playbook: docker/nas1_icloudpd.yml
- import_playbook: docker/nas1_unpackerr.yml
- import_playbook: docker/nas1_zigbee2mqtt.yml
- import_playbook: docker/nodes_portainer_agent.yml
- import_playbook: docker/public_caddy_proxy.yml
- import_playbook: docker/public_cloudflared.yml
- import_playbook: docker/vps_portainer_agent.yml
- import_playbook: docker/vps1_caddy_proxy.yml
- import_playbook: docker/vps1_compose_updates.yml
- import_playbook: docker/vps2_caddy_proxy.yml
- import_playbook: docker/vps2_coredns.yml
- import_playbook: docker/vps2_linkstack.yml
- import_playbook: docker/vps2_mariadb.yml
- import_playbook: docker/vps2_shlink.yml
- import_playbook: docker_prune.yml
