---

- name: update all unix boxes
  hosts: thunderweb
  become: true
  gather_facts: true
  tasks:
  - package:
      name: "*"
      state: latest
    register: package_update

- name: update rkhunter on topcat
  hosts: topcat.thunderweb.co.uk
  become: true
  gather_facts: false
  tasks:
  - command:
      cmd: rkhunter --propupd
    when: package_update is changed

- name: update nextcloud on drive.thunderweb.uk
  hosts: topcat.thunderweb.co.uk
  become: true
  become_user: nginx
  gather_facts: false
  tasks:
  - command:
      cmd: php /home/websites/thunderweb.uk/drive/public_html/updater/updater.phar --no-interaction

- name: update homebrew
  hosts: localhost
  tasks:
  - homebrew:
      update_homebrew: yes
      upgrade_all: yes
