---

- name: update all linux boxes
  hosts: linuxboxes
  become: true
  gather_facts: true
  tasks:
  - name: Update all packages to their latest version
    ansible.builtin.apt:
      clean: yes
      update_cache: yes
      autoremove: yes
      name: "*"
      state: latest
    when: ansible_facts['os_family'] == "Debian"
    
#  - package:
#      name: "*"
#      state: latest
#    when: ansible_facts['os_family'] != "Debian"

#- name: update homebrew
#  hosts: localhost
#  - homebrew:
#  tasks:
#      update_homebrew: yes
#      upgrade_all: yes
