---

- name: update all linux boxes
  hosts: thunderweb
  become: true
  tasks:
  - package:
      name: "*"
      state: latest
    register: package_update

- name: update rkhunter on topcat
  hosts: topcat.thunderweb.co.uk
  become: true
  tasks:
  - command:
      cmd: rkhunter --propupd
    when: package_update is changed

- name: update homebrew
  hosts: localhost
  tasks:
  - homebrew:
      update_homebrew: yes
      upgrade_all: yes
