---

- name: update all linux boxes
  hosts: linuxboxes
  become: true
  gather_facts: true
  tasks:
  - package:
      name: "*"
      state: latest
    register: package_update

- name: update homebrew
  hosts: localhost
  tasks:
  - homebrew:
      update_homebrew: yes
      upgrade_all: yes

- import_playbook: pihole.yml
