---

- name: update all linux boxes
  hosts: linuxboxes
  become: true
  gather_facts: true
  tasks:
  - package:
      name: "*"
      state: latest
    register: package_update
  - ansible.builtin.apt:
      autoremove: yes
    when: ansible_facts['os_family'] == "Debian"

- name: update homebrew
  hosts: localhost
  tasks:
  - homebrew:
      update_homebrew: yes
      upgrade_all: yes
