---

- name: update all unix boxes
  hosts: thunderweb
  become: true
  gather_facts: true
  tasks:
  - package:
      name: "*"
      state: latest
    register: package_update

- name: update rkhunter on topcat
  hosts: topcat.thunderweb.co.uk
  become: true
  gather_facts: false
  tasks:
  - command:
      cmd: rkhunter --propupd
    when: package_update is changed

- name: update pihole on raspberrypi
  hosts: raspberrypi.thunderweb.co.uk
  become: true
  gather_facts: false
  tasks:
  - command:
      cmd: /usr/local/bin/pihole -up

- name: update homebrew
  hosts: localhost
  tasks:
  - homebrew:
      update_homebrew: yes
      upgrade_all: yes

- import_playbook: wordpress.yml
- import_playbook: nextcloud.yml
