---

- name: update wordpress installs
  hosts: topcat.thunderweb.co.uk
  become: true
  become_user: nginx
  gather_facts: false
  vars:
    wordpress_installs:
      - "/home/websites/drunkendba.co.uk/public_html"
      - "/home/websites/scottclark.me.uk/www/public_html/"
      - "/home/websites/scottclark.uk/dev/public_html"

  tasks:
    - name: update wordpress 
      include_tasks: wordpress_update.yml
      loop: "{{ wordpress_installs }}"

