---
- name: install home assistant on docker1
  hosts: docker1.thunderweb.co.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: homeassistant
        image: lscr.io/linuxserver/homeassistant:latest
        pull: true
        hostname: homeassistant
        restart_policy: always
        network_mode: host
        privileged: true
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
          DOCKER_MODS: "linuxserver/mods:homeassistant-hacs"
        volumes:
          - homeassistant_data:/config
          - /run/dbus:/run/dbus:ro