---
- name: install homepage on docker1
  hosts: docker1.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: homepage
        image: ghcr.io/gethomepage/homepage:latest
        pull: true
        hostname: homepage
        restart_policy: always
        networks:
          - name: web
        env:
          HOMEPAGE_ALLOWED_HOSTS: "homepage.home.thunderweb.uk"
        volumes:
          - homepage_data:/app/config
        ports:
        labels:
          caddy: homepage.home.thunderweb.uk
          caddy.import_0: httpauth
          caddy.import_1: accesslogs
          caddy.reverse_proxy: !unsafe "{{ upstreams 3000 }}"
    - name: Create homepage.home.thunderweb.uk CNAME
      delegate_to: localhost
      ansible.builtin.uri:
        url: https://dns.srv.3fr.uk/api/zones/records/add
        method: POST
        body_format: form-urlencoded
        body:
          token: "{{ dns_token }}"
          domain: homepage.home.thunderweb.uk
          type: CNAME
          cname: "{{ inventory_hostname }}"
          overwrite: true
        status_code: 200