---
- name: install pdns-auth on pihole
  hosts: pihole.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: pdns
        image: powerdns/pdns-auth-49:latest
        pull: true
        restart_policy: always
        env:
          PDNS_AUTH_API_KEY: "{{ pdns_auth_api }}"
        volumes:
          - pdns_data:/var/lib/powerdns/
        ports:
          - "5553:53"
          - "5553:53/udp"
          - "8081:8081"
