---
- name: install plex on plex
  hosts: plex.srv.3fr.uk
  gather_facts: false
  tasks:
    - community.docker.docker_container:
        name: plex
        image: plexinc/pms-docker:plexpass
        pull: true
        hostname: plex
        restart_policy: always
        network_mode: host
        env:
          PLEX_UID: "1000"
          PLEX_GID: "1000"
          TZ: "Europe/London"
          PLEX_CLAIM: "claim-i9rJjZRxoSsmH6FtF_2F"
        volumes:
          - plex_data:/config
          - /data/media:/data/media
          - /opt/plex/transcode:/transcode
        devices:
          - /dev/dri:/dev/dri
